"use server";

import { asc, desc, eq } from "drizzle-orm";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { z } from "zod";
import { db } from "@/db";
import { postCaseLinks, postIssueLinks, posts, postTypeEnum } from "@/db/schema";
import { InvalidCasePhotoError, uploadCasePhoto } from "@/lib/case-photo-storage";
import type { ContentDraftInput } from "@/lib/content-draft";
import { getContentDraftJobStatus, setContentDraftJobStatus, type ContentDraftJobStatus } from "@/lib/content-draft-jobs";
import { attachContentSources, removeContentSourceRow } from "@/lib/content-sources";
import { requireAdmin } from "@/lib/require-admin";
import { insertWithUniqueSlug } from "@/lib/unique-slug";

const postFormSchema = z.object({
  type: z.enum(postTypeEnum.enumValues),
  title: z.string().min(1),
  body: z.string().min(1),
  whyThisMatters: z.string().optional(),
  whatToWatch: z.string().optional(),
  state: z.string().optional(),
  imageUrl: z.string().optional(),
  sourceIntelligenceItemId: z.string().optional(),
});

/** A newly uploaded file replaces the photo; otherwise the hidden
 * `imageUrl` field (the source's own image, or whatever the post already
 * had) carries forward. Same pattern as cases/actions.ts's photo handling. */
async function resolvePostImageUrl(formData: FormData, fallbackImageUrl: string | undefined): Promise<string | null> {
  const photoFile = formData.get("photo");
  if (photoFile instanceof File && photoFile.size > 0) {
    return uploadCasePhoto(photoFile);
  }
  return fallbackImageUrl?.trim() || null;
}

function parsePostForm(formData: FormData) {
  const raw = Object.fromEntries(formData.entries());
  const parsed = postFormSchema.parse(raw);
  return {
    ...parsed,
    whatToWatch: (parsed.whatToWatch ?? "")
      .split("\n")
      .map((line) => line.trim())
      .filter(Boolean),
    caseIds: formData.getAll("caseIds").map(String).filter(Boolean),
    issueTags: formData.getAll("issueTags").map(String).filter(Boolean),
    additionalSourceIds: formData.getAll("additionalSourceIds").map(String).filter(Boolean),
  };
}

/** Replaces a post's related-case/related-issue connections wholesale —
 * simplest correct behavior for both create (nothing to clear) and edit
 * (the form always submits the full current selection). */
async function setCaseAndIssueLinks(postId: string, caseIds: string[], issueTags: string[]) {
  await db.delete(postCaseLinks).where(eq(postCaseLinks.postId, postId));
  await db.delete(postIssueLinks).where(eq(postIssueLinks.postId, postId));
  if (caseIds.length > 0) {
    await db.insert(postCaseLinks).values(caseIds.map((caseId) => ({ postId, caseId })));
  }
  if (issueTags.length > 0) {
    await db.insert(postIssueLinks).values(issueTags.map((issueTag) => ({ postId, issueTag })));
  }
}

export async function createPost(formData: FormData) {
  await requireAdmin();
  const data = parsePostForm(formData);

  let imageUrl: string | null;
  try {
    imageUrl = await resolvePostImageUrl(formData, data.imageUrl);
  } catch (err) {
    if (err instanceof InvalidCasePhotoError) {
      const params = new URLSearchParams({ type: data.type, photoError: err.message });
      if (data.sourceIntelligenceItemId) params.set("fromIntelligence", data.sourceIntelligenceItemId);
      redirect(`/admin/posts/new?${params}`);
    }
    throw err;
  }

  const row = await insertWithUniqueSlug(data.title, (slug) =>
    db
      .insert(posts)
      .values({
        type: data.type,
        title: data.title,
        slug,
        body: data.body,
        whyThisMatters: data.whyThisMatters?.trim() || null,
        whatToWatch: data.whatToWatch,
        state: data.state?.trim() || null,
        imageUrl,
        status: "pending",
        autoGenerated: false,
      })
      .returning({ id: posts.id }),
  );

  const sourceItemIds = [data.sourceIntelligenceItemId, ...data.additionalSourceIds].filter(
    (id): id is string => Boolean(id),
  );
  await attachContentSources("post", row.id, sourceItemIds);
  await setCaseAndIssueLinks(row.id, data.caseIds, data.issueTags);

  revalidatePath("/admin/posts");
  revalidatePath("/admin/intelligence");
  redirect(`/admin/posts/${row.id}?saved=1`);
}

export async function updatePost(postId: string, formData: FormData) {
  await requireAdmin();
  const data = parsePostForm(formData);

  let imageUrl: string | null;
  try {
    imageUrl = await resolvePostImageUrl(formData, data.imageUrl);
  } catch (err) {
    if (err instanceof InvalidCasePhotoError) {
      redirect(`/admin/posts/${postId}?photoError=${encodeURIComponent(err.message)}`);
    }
    throw err;
  }

  await db
    .update(posts)
    .set({
      type: data.type,
      title: data.title,
      body: data.body,
      whyThisMatters: data.whyThisMatters?.trim() || null,
      whatToWatch: data.whatToWatch,
      state: data.state?.trim() || null,
      imageUrl,
    })
    .where(eq(posts.id, postId));

  await attachContentSources("post", postId, data.additionalSourceIds);
  await setCaseAndIssueLinks(postId, data.caseIds, data.issueTags);

  revalidatePath("/admin/posts");
  revalidatePath(`/admin/posts/${postId}`);
  redirect(`/admin/posts/${postId}?saved=1`);
}

/** Removes one attached source from a post. Deliberately doesn't reset the
 * intelligenceItems row back to "used: false" — a source can be legitimately
 * removed from one draft while still correctly counting as used elsewhere. */
export async function removeContentSource(postId: string, contentSourceId: string) {
  await requireAdmin();
  await removeContentSourceRow(contentSourceId);
  revalidatePath(`/admin/posts/${postId}`);
  revalidatePath("/admin/intelligence/sources");
}

export type StartContentDraftResult = { ok: true; jobId: string } | { ok: false; error: string };

/** Kicks off a background job that drafts a post body from its source via
 * Claude — Analysis/Explainer use web_search at high effort and reliably
 * take 20-40+ seconds, well past what a Server Action can run inline before
 * Netlify kills the request (confirmed live: "An unexpected response was
 * received from the server"). Same class of problem
 * startCaseOverviewExtraction (cases/actions.ts) already exists to solve,
 * so this stores a pending job and fires a background function the same
 * way rather than awaiting Claude here. Nothing is saved to the database —
 * see draft-body-button.tsx, which fills the body textarea client-side for
 * the editor to review (and then explicitly save) once the job completes. */
export async function startContentDraft(input: ContentDraftInput): Promise<StartContentDraftResult> {
  await requireAdmin();

  const jobId = crypto.randomUUID();
  await setContentDraftJobStatus(jobId, { status: "pending" });

  const origin = process.env.URL ?? process.env.DEPLOY_PRIME_URL;
  const secret = process.env.DAILY_CONTENT_SECRET;
  if (!origin || !secret) {
    console.error("startContentDraft: missing URL or DAILY_CONTENT_SECRET env var");
    return { ok: false, error: "Drafting isn't configured on this deploy yet." };
  }

  try {
    await fetch(`${origin}/.netlify/functions/content-draft-background`, {
      method: "POST",
      headers: { "x-internal-job-secret": secret, "content-type": "application/json" },
      body: JSON.stringify({ jobId, input }),
    });
  } catch (err) {
    console.error("startContentDraft: failed to dispatch background job", err);
    return { ok: false, error: "Couldn't start drafting. Try again." };
  }

  return { ok: true, jobId };
}

export async function getContentDraftStatus(jobId: string): Promise<ContentDraftJobStatus> {
  await requireAdmin();
  return getContentDraftJobStatus(jobId);
}

export async function approvePost(postId: string) {
  await requireAdmin();
  await db
    .update(posts)
    .set({ status: "published", publishedAt: new Date() })
    .where(eq(posts.id, postId));
  revalidatePath("/admin/posts");
  revalidatePath(`/admin/posts/${postId}`);
  redirect(`/admin/posts/${postId}?saved=1`);
}

export async function deletePost(postId: string) {
  await requireAdmin();
  await db.delete(posts).where(eq(posts.id, postId));
  revalidatePath("/admin/posts");
  redirect("/admin/posts?saved=deleted");
}

/** Moves a post one spot up or down in the admin/public display order.
 * Rewrites sortOrder for every post as its index in the new order rather
 * than swapping the two raw values, since most rows share the same
 * default (0) until the first reorder happens — a plain swap between two
 * equal values would silently do nothing. */
export async function movePost(postId: string, direction: "up" | "down") {
  await requireAdmin();

  const rows = await db
    .select({ id: posts.id })
    .from(posts)
    .orderBy(asc(posts.sortOrder), desc(posts.createdAt));
  const ids = rows.map((r) => r.id);

  const index = ids.indexOf(postId);
  const swapWith = direction === "up" ? index - 1 : index + 1;
  if (index === -1 || swapWith < 0 || swapWith >= ids.length) return;

  [ids[index], ids[swapWith]] = [ids[swapWith], ids[index]];
  await Promise.all(ids.map((id, i) => db.update(posts).set({ sortOrder: i }).where(eq(posts.id, id))));

  revalidatePath("/admin/posts");
  revalidatePath("/posts");
  revalidatePath("/");
}
