import { desc } from "drizzle-orm";
import Link from "next/link";
import { db } from "@/db";
import { posts } from "@/db/schema";

export default async function AdminPostsPage() {
  const rows = await db.select().from(posts).orderBy(desc(posts.createdAt));

  return (
    <div>
      <h1 className="font-serif text-2xl text-foreground">Posts</h1>
      {rows.length === 0 ? (
        <p className="mt-6 text-sm text-muted">
          No posts yet. The daily content pipeline writes drafts here for review.
        </p>
      ) : (
        <table className="mt-6 w-full text-left text-sm">
          <thead className="text-muted">
            <tr className="border-b border-border">
              <th className="py-2 font-medium">Title</th>
              <th className="py-2 font-medium">Type</th>
              <th className="py-2 font-medium">Status</th>
              <th className="py-2 font-medium">Auto-generated</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row) => (
              <tr key={row.id} className="border-b border-border">
                <td className="py-2 text-foreground">
                  <Link href={`/admin/posts/${row.id}`} className="underline">
                    {row.title}
                  </Link>
                </td>
                <td className="py-2 text-foreground">{row.type}</td>
                <td className="py-2 text-foreground">{row.status}</td>
                <td className="py-2 text-foreground">{row.autoGenerated ? "Yes" : "No"}</td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}
