import { asc, desc } from "drizzle-orm";
import Link from "next/link";
import { PostReorderTable } from "./post-reorder-table";
import { db } from "@/db";
import { posts } from "@/db/schema";

export default async function AdminPostsPage() {
  const rows = await db
    .select({
      id: posts.id,
      title: posts.title,
      type: posts.type,
      status: posts.status,
      autoGenerated: posts.autoGenerated,
    })
    .from(posts)
    .orderBy(asc(posts.sortOrder), desc(posts.createdAt));

  return (
    <div>
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="font-serif text-2xl text-foreground">Editorial content</h1>
          <p className="mt-1 text-sm text-muted">
            News briefs, case developments, analysis, and everything else created via Xonorate
            Intelligence&apos;s &quot;Create With This&quot;, plus any older auto-generated roundups.
            Publish a draft to send it live on the public site. Drag a row (or use the arrows) to
            change its order in the homepage&apos;s &quot;Beyond the headline&quot; section — or click
            Feature to send a published one straight to the top.
          </p>
        </div>
        <Link
          href="/admin/posts/new"
          className="shrink-0 rounded-md bg-brand px-3 py-1.5 text-sm font-medium text-brand-foreground hover:opacity-90"
        >
          New
        </Link>
      </div>
      {rows.length === 0 ? (
        <p className="mt-6 text-sm text-muted">
          Nothing here yet. Create content directly, or from a discovered story at{" "}
          <Link href="/admin/intelligence" className="underline">
            Xonorate Intelligence
          </Link>
          .
        </p>
      ) : (
        <PostReorderTable initialRows={rows} />
      )}
    </div>
  );
}
