import { asc, desc } from "drizzle-orm";
import Link from "next/link";
import { Badge } from "@/app/admin/_components/field";
import { PostReorderButtons } from "./post-reorder-buttons";
import { db } from "@/db";
import { posts } from "@/db/schema";
import { POST_STATUS_LABEL, POST_TYPE_LABEL } from "@/lib/post-type";

export default async function AdminPostsPage() {
  const rows = await db
    .select()
    .from(posts)
    .orderBy(asc(posts.sortOrder), desc(posts.createdAt));

  return (
    <div>
      <div className="flex items-start justify-between gap-4">
        <div>
          <h1 className="font-serif text-2xl text-foreground">Editorial content</h1>
          <p className="mt-1 text-sm text-muted">
            News briefs, case developments, analysis, and everything else created via Xonorate
            Intelligence&apos;s &quot;Create With This&quot;, plus any older auto-generated roundups.
            Publish a draft to send it live on the public site.
          </p>
        </div>
        <Link
          href="/admin/posts/new"
          className="shrink-0 rounded-md bg-brand px-3 py-1.5 text-sm font-medium text-brand-foreground hover:opacity-90"
        >
          New
        </Link>
      </div>
      {rows.length === 0 ? (
        <p className="mt-6 text-sm text-muted">
          Nothing here yet. Create content directly, or from a discovered story at{" "}
          <Link href="/admin/intelligence" className="underline">
            Xonorate Intelligence
          </Link>
          .
        </p>
      ) : (
        <table className="mt-6 w-full text-left text-sm">
          <thead className="text-muted">
            <tr className="border-b border-border">
              <th className="py-2 font-medium" />
              <th className="py-2 font-medium">Title</th>
              <th className="py-2 font-medium">Type</th>
              <th className="py-2 font-medium">Status</th>
              <th className="py-2 font-medium">Source</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((row, i) => (
              <tr key={row.id} className="border-b border-border">
                <td className="py-2">
                  <PostReorderButtons postId={row.id} isFirst={i === 0} isLast={i === rows.length - 1} />
                </td>
                <td className="py-2 text-foreground">
                  <Link href={`/admin/posts/${row.id}`} className="underline">
                    {row.title}
                  </Link>
                </td>
                <td className="py-2">
                  <Badge tone="brand">{POST_TYPE_LABEL[row.type] ?? row.type}</Badge>
                </td>
                <td className="py-2">
                  <Badge tone={row.status === "published" ? "brand" : "neutral"}>
                    {POST_STATUS_LABEL[row.status] ?? row.status}
                  </Badge>
                </td>
                <td className="py-2">
                  {row.autoGenerated ? (
                    <Badge tone="neutral">AI-generated</Badge>
                  ) : (
                    <span className="text-muted">Manual</span>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      )}
    </div>
  );
}
