"use client";

import Link from "next/link";
import { useRef, useState, useTransition } from "react";
import { Badge } from "@/app/admin/_components/field";
import { POST_STATUS_LABEL, POST_TYPE_LABEL } from "@/lib/post-type";
import { featurePost, movePost, setPostOrder } from "./actions";

export type PostReorderRow = {
  id: string;
  title: string;
  type: string;
  status: string;
  autoGenerated: boolean;
};

/** The /admin/posts table, in charge of "Beyond the headline"'s ordering
 * (see setPostOrder/movePost/featurePost in actions.ts — all three funnel
 * into the same sortOrder rewrite). Drag-and-drop is the primary way to
 * reorder; the arrows stay for anyone not dragging (keyboard use, or just
 * finer single-step control), and "Feature" jumps a post straight to the
 * top without dragging it past everything above it. Reorders optimistically
 * (local state moves immediately on drop) since waiting on the server
 * round-trip would make dragging feel laggy. */
export function PostReorderTable({ initialRows }: { initialRows: PostReorderRow[] }) {
  const [rows, setRows] = useState(initialRows);
  const [isPending, startTransition] = useTransition();
  const dragIndexRef = useRef<number | null>(null);
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null);

  function commitOrder(next: PostReorderRow[]) {
    setRows(next);
    startTransition(() => {
      setPostOrder(next.map((r) => r.id));
    });
  }

  function handleDrop(targetIndex: number) {
    const from = dragIndexRef.current;
    dragIndexRef.current = null;
    setDragOverIndex(null);
    if (from === null || from === targetIndex) return;

    const next = [...rows];
    const [moved] = next.splice(from, 1);
    next.splice(targetIndex, 0, moved);
    commitOrder(next);
  }

  function handleMove(postId: string, direction: "up" | "down") {
    const index = rows.findIndex((r) => r.id === postId);
    const swapWith = direction === "up" ? index - 1 : index + 1;
    if (index === -1 || swapWith < 0 || swapWith >= rows.length) return;

    const next = [...rows];
    [next[index], next[swapWith]] = [next[swapWith], next[index]];
    setRows(next);
    startTransition(() => {
      movePost(postId, direction);
    });
  }

  function handleFeature(postId: string) {
    const index = rows.findIndex((r) => r.id === postId);
    if (index <= 0) return;

    const next = [...rows];
    const [moved] = next.splice(index, 1);
    next.unshift(moved);
    setRows(next);
    startTransition(() => {
      featurePost(postId);
    });
  }

  return (
    <table className="mt-6 w-full text-left text-sm">
      <thead className="text-muted">
        <tr className="border-b border-border">
          <th className="py-2 font-medium" />
          <th className="py-2 font-medium">Title</th>
          <th className="py-2 font-medium">Type</th>
          <th className="py-2 font-medium">Status</th>
          <th className="py-2 font-medium">Source</th>
          <th className="py-2 font-medium" />
        </tr>
      </thead>
      <tbody className={isPending ? "opacity-60 transition" : "transition"}>
        {rows.map((row, i) => (
          <tr
            key={row.id}
            draggable
            onDragStart={() => {
              dragIndexRef.current = i;
            }}
            onDragOver={(e) => {
              e.preventDefault();
              setDragOverIndex(i);
            }}
            onDragLeave={() => setDragOverIndex((cur) => (cur === i ? null : cur))}
            onDrop={(e) => {
              e.preventDefault();
              handleDrop(i);
            }}
            onDragEnd={() => {
              dragIndexRef.current = null;
              setDragOverIndex(null);
            }}
            className={`border-b border-border ${dragOverIndex === i ? "bg-muted-background" : ""}`}
          >
            <td className="w-16 py-2">
              <div className="flex items-center gap-1.5">
                <span
                  className="cursor-grab select-none text-base leading-none text-muted active:cursor-grabbing"
                  title="Drag to reorder"
                  aria-hidden
                >
                  ⠿
                </span>
                <div className="flex flex-col">
                  <button
                    type="button"
                    aria-label="Move up"
                    disabled={isPending || i === 0}
                    onClick={() => handleMove(row.id, "up")}
                    className="leading-none text-muted transition hover:text-foreground disabled:opacity-30"
                  >
                    ▲
                  </button>
                  <button
                    type="button"
                    aria-label="Move down"
                    disabled={isPending || i === rows.length - 1}
                    onClick={() => handleMove(row.id, "down")}
                    className="leading-none text-muted transition hover:text-foreground disabled:opacity-30"
                  >
                    ▼
                  </button>
                </div>
              </div>
            </td>
            <td className="py-2 text-foreground">
              <Link href={`/admin/posts/${row.id}`} className="underline">
                {row.title}
              </Link>
            </td>
            <td className="py-2">
              <Badge tone="brand">{POST_TYPE_LABEL[row.type] ?? row.type}</Badge>
            </td>
            <td className="py-2">
              <Badge tone={row.status === "published" ? "brand" : "neutral"}>
                {POST_STATUS_LABEL[row.status] ?? row.status}
              </Badge>
            </td>
            <td className="py-2">
              {row.autoGenerated ? <Badge tone="neutral">AI-generated</Badge> : <span className="text-muted">Manual</span>}
            </td>
            <td className="py-2 text-right">
              {i > 0 && (
                <button
                  type="button"
                  disabled={isPending}
                  onClick={() => handleFeature(row.id)}
                  className="text-xs text-brand underline disabled:opacity-30"
                  title="Move straight to the top of Beyond the headline"
                >
                  Feature
                </button>
              )}
            </td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}
