import { asc, desc } from "drizzle-orm";
import { db } from "@/db";
import { posts } from "@/db/schema";

// THROWAWAY read-only diagnostic: check post ordering/status/autoGenerated
// to figure out why manually-added posts appear to be missing the
// "Feature" link in the admin table. Delete this route once checked.
export async function GET(request: Request) {
  const secret = request.headers.get("x-daily-content-secret");
  if (!process.env.DAILY_CONTENT_SECRET || secret !== process.env.DAILY_CONTENT_SECRET) {
    return new Response("Forbidden", { status: 403 });
  }

  const rows = await db
    .select({
      id: posts.id,
      title: posts.title,
      status: posts.status,
      autoGenerated: posts.autoGenerated,
      sortOrder: posts.sortOrder,
      createdAt: posts.createdAt,
    })
    .from(posts)
    .orderBy(asc(posts.sortOrder), desc(posts.createdAt));

  return Response.json(rows);
}
