import { eq } from "drizzle-orm";
import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/db";
import { cases, posts } from "@/db/schema";
import { POST_TYPE_LABEL } from "@/lib/post-type";
import { approvePost, deletePost } from "../actions";

export default async function AdminPostDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  const [post] = await db.select().from(posts).where(eq(posts.id, id)).limit(1);
  if (!post) notFound();

  const linkedCase = post.caseId
    ? (
        await db
          .select({ clientName: cases.clientName, slug: cases.slug })
          .from(cases)
          .where(eq(cases.id, post.caseId))
          .limit(1)
      )[0]
    : null;

  const sources = post.sources as { url: string; title: string }[];

  return (
    <div className="max-w-2xl">
      <div className="flex items-center justify-between">
        <div>
          <p className="text-xs font-medium uppercase tracking-wide text-brand">
            {POST_TYPE_LABEL[post.type] ?? post.type} · {post.status}
            {post.autoGenerated && " · auto-generated"}
          </p>
          <h1 className="mt-1 font-serif text-2xl text-foreground">{post.title}</h1>
        </div>
        <div className="flex gap-2">
          {post.status === "pending" && (
            <form action={approvePost.bind(null, post.id)}>
              <button
                type="submit"
                className="rounded-md bg-brand px-3 py-1.5 text-sm font-medium text-brand-foreground hover:opacity-90"
              >
                Approve &amp; publish
              </button>
            </form>
          )}
          <form action={deletePost.bind(null, post.id)}>
            <button type="submit" className="rounded-md border border-border px-3 py-1.5 text-sm text-red-600">
              Delete
            </button>
          </form>
        </div>
      </div>

      {linkedCase && (
        <p className="mt-2 text-sm text-muted">
          About:{" "}
          <Link href={`/admin/cases/${post.caseId}/edit`} className="underline">
            {linkedCase.clientName}
          </Link>
        </p>
      )}
      {post.state && <p className="mt-1 text-sm text-muted">State: {post.state}</p>}

      <article className="mt-6 whitespace-pre-wrap rounded-lg border border-border p-5 text-sm text-foreground">
        {post.body}
      </article>

      <h2 className="mt-8 font-serif text-lg text-foreground">Sources</h2>
      {sources.length === 0 ? (
        <p className="mt-2 text-sm text-muted">No sources listed.</p>
      ) : (
        <ul className="mt-3 space-y-1 text-sm">
          {sources.map((s, i) => (
            <li key={i}>
              <a href={s.url} className="text-brand underline" target="_blank" rel="noopener noreferrer">
                {s.title}
              </a>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
